USE oblms;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE courses;
TRUNCATE TABLE curriculum_subjects;
INSERT INTO courses (id, code, title, faculty, semester) VALUES (101, 'CS111', 'Calculus & Linear Algebra', 'Dr. Satish Sharma', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (1, 'CS111', 'Calculus & Linear Algebra', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (102, 'CS112', 'Applied Engineering Physics', 'Prof. Ananya Sen', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (2, 'CS112', 'Applied Engineering Physics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (103, 'CS113', 'Problem Solving and Programming in C', 'Dr. Ramesh Babu', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (3, 'CS113', 'Problem Solving and Programming in C', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (104, 'CS114', 'Basic Electrical & Electronics Engineering', 'Dr. Priya Nair', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (4, 'CS114', 'Basic Electrical & Electronics Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (105, 'CS111L', 'C Programming Laboratory', 'Dr. Ramesh Babu', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (5, 'CS111L', 'C Programming Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (106, 'CS121', 'Advanced Differential Equations & Transforms', 'Dr. Satish Sharma', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (6, 'CS121', 'Advanced Differential Equations & Transforms', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (107, 'CS122', 'Engineering Chemistry & Materials Science', 'Prof. Meenakshi Sundaram', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (7, 'CS122', 'Engineering Chemistry & Materials Science', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (108, 'CS123', 'Python Programming for Problem Solving', 'Prof. Sunita Sharma', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (8, 'CS123', 'Python Programming for Problem Solving', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (109, 'CS124', 'Basic Mechanical & Civil Engineering', 'Dr. K. Srinivas', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (9, 'CS124', 'Basic Mechanical & Civil Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (110, 'CS121L', 'Python Programming Laboratory', 'Prof. Sunita Sharma', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (10, 'CS121L', 'Python Programming Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (1, 'CS101', 'Database Management Systems', 'Dr. Ramesh Babu', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (11, 'CS101', 'Database Management Systems', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (2, 'CS102', 'Data Structures & Algorithms', 'Prof. Sunita Sharma', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (12, 'CS102', 'Data Structures & Algorithms', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (3, 'CS103', 'Object-Oriented Programming with Java', 'Dr. Ramesh Babu', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (13, 'CS103', 'Object-Oriented Programming with Java', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (111, 'CS203', 'Discrete Mathematical Structures', 'Dr. Satish Sharma', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (14, 'CS203', 'Discrete Mathematical Structures', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (112, 'CS101L', 'DBMS & SQL Practical Laboratory', 'Dr. Ramesh Babu', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (15, 'CS101L', 'DBMS & SQL Practical Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (4, 'CS201', 'Operating Systems & Kernel Architecture', 'Dr. Amit Patel', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (16, 'CS201', 'Operating Systems & Kernel Architecture', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (113, 'CS205', 'Design and Analysis of Algorithms', 'Prof. Sunita Sharma', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (17, 'CS205', 'Design and Analysis of Algorithms', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (114, 'CS206', 'Formal Languages & Automata Theory', 'Prof. Rajesh Verma', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (18, 'CS206', 'Formal Languages & Automata Theory', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (115, 'CS207', 'Computer Organization & Architecture', 'Dr. Priya Nair', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (19, 'CS207', 'Computer Organization & Architecture', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (116, 'CS201L', 'Operating Systems Laboratory', 'Dr. Amit Patel', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (20, 'CS201L', 'Operating Systems Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (6, 'CS301', 'Computer Networks & Protocols', 'Dr. Priya Nair', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (21, 'CS301', 'Computer Networks & Protocols', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (5, 'CS202', 'Machine Learning & Data Science', 'Prof. Sunita Sharma', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (22, 'CS202', 'Machine Learning & Data Science', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (117, 'CS304', 'Database System Implementation & Tuning', 'Dr. Ramesh Babu', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (23, 'CS304', 'Database System Implementation & Tuning', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (118, 'CS306', 'Web Technologies & Modern Frameworks', 'Dr. Amit Patel', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (24, 'CS306', 'Web Technologies & Modern Frameworks', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (119, 'CS301L', 'Computer Networks Laboratory', 'Dr. Priya Nair', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (25, 'CS301L', 'Computer Networks Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (7, 'CS302', 'Software Engineering & Agile Methodologies', 'Prof. Rajesh Verma', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (26, 'CS302', 'Software Engineering & Agile Methodologies', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (8, 'CS303', 'Cloud Computing & DevOps Architecture', 'Dr. Amit Patel', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (27, 'CS303', 'Cloud Computing & DevOps Architecture', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (120, 'CS307', 'Compiler Design & Program Analysis', 'Dr. Ramesh Babu', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (28, 'CS307', 'Compiler Design & Program Analysis', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (121, 'CS308', 'Artificial Intelligence Principles', 'Prof. Sunita Sharma', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (29, 'CS308', 'Artificial Intelligence Principles', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (122, 'CS302L', 'Software Engineering & CASE Tools Lab', 'Prof. Rajesh Verma', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (30, 'CS302L', 'Software Engineering & CASE Tools Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (9, 'CS401', 'Deep Learning & Neural Networks', 'Dr. Ramesh Babu', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (31, 'CS401', 'Deep Learning & Neural Networks', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (10, 'CS402', 'Cyber Security & Digital Forensics', 'Prof. Rajesh Verma', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (32, 'CS402', 'Cyber Security & Digital Forensics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (123, 'CS403', 'Big Data Analytics & Distributed Systems', 'Dr. Amit Patel', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (33, 'CS403', 'Big Data Analytics & Distributed Systems', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (124, 'CS405', 'Natural Language Processing', 'Prof. Sunita Sharma', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (34, 'CS405', 'Natural Language Processing', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (125, 'CS401L', 'Deep Learning & AI Research Laboratory', 'Dr. Ramesh Babu', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (35, 'CS401L', 'Deep Learning & AI Research Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (126, 'CS411', 'Internet of Things (IoT) & Edge Computing', 'Dr. Priya Nair', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (36, 'CS411', 'Internet of Things (IoT) & Edge Computing', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (127, 'CS413', 'Blockchain Technology & Smart Contracts', 'Dr. Amit Patel', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (37, 'CS413', 'Blockchain Technology & Smart Contracts', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (128, 'CS414', 'Autonomous Agents & Reinforcement Learning', 'Prof. Sunita Sharma', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (38, 'CS414', 'Autonomous Agents & Reinforcement Learning', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (129, 'CS498', 'Major Capstone Project Phase II', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (39, 'CS498', 'Major Capstone Project Phase II', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (130, 'CS499', 'Comprehensive Curriculum Viva Voce', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (40, 'CS499', 'Comprehensive Curriculum Viva Voce', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (201, 'IT111', 'Calculus for Computing Sciences', 'Dr. Satish Sharma', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (41, 'IT111', 'Calculus for Computing Sciences', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (202, 'IT112', 'Applied Physics for Information Science', 'Prof. Ananya Sen', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (42, 'IT112', 'Applied Physics for Information Science', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (203, 'IT113', 'Problem Solving with C', 'Dr. Amit Patel', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (43, 'IT113', 'Problem Solving with C', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (204, 'IT114', 'Introduction to Information Technology', 'Prof. Rajesh Verma', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (44, 'IT114', 'Introduction to Information Technology', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (205, 'IT111L', 'C Programming Laboratory', 'Dr. Amit Patel', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (45, 'IT111L', 'C Programming Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (206, 'IT121', 'Differential Equations & Numerical Methods', 'Dr. Satish Sharma', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (46, 'IT121', 'Differential Equations & Numerical Methods', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (207, 'IT122', 'Chemistry of Electronic Materials', 'Prof. Meenakshi Sundaram', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (47, 'IT122', 'Chemistry of Electronic Materials', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (208, 'IT123', 'Python Programming for IT', 'Prof. Sunita Sharma', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (48, 'IT123', 'Python Programming for IT', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (209, 'IT124', 'Basics of Electrical & Electronics Engineering', 'Dr. Priya Nair', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (49, 'IT124', 'Basics of Electrical & Electronics Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (210, 'IT121L', 'Python Laboratory', 'Prof. Sunita Sharma', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (50, 'IT121L', 'Python Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (211, 'IT201', 'Data Structures using C++', 'Prof. Sunita Sharma', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (51, 'IT201', 'Data Structures using C++', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (212, 'IT202', 'Object-Oriented Programming with Java', 'Dr. Ramesh Babu', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (52, 'IT202', 'Object-Oriented Programming with Java', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (213, 'IT203', 'Discrete Mathematics for IT', 'Dr. Satish Sharma', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (53, 'IT203', 'Discrete Mathematics for IT', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (214, 'IT204', 'Digital Electronics and Logic Design', 'Dr. Priya Nair', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (54, 'IT204', 'Digital Electronics and Logic Design', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (215, 'IT201L', 'Data Structures Laboratory', 'Prof. Sunita Sharma', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (55, 'IT201L', 'Data Structures Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (216, 'IT211', 'Operating Systems Administration', 'Dr. Amit Patel', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (56, 'IT211', 'Operating Systems Administration', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (217, 'IT212', 'Relational Database Management Systems', 'Dr. Ramesh Babu', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (57, 'IT212', 'Relational Database Management Systems', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (218, 'IT213', 'Design & Analysis of IT Algorithms', 'Prof. Sunita Sharma', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (58, 'IT213', 'Design & Analysis of IT Algorithms', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (219, 'IT214', 'Theory of Computation & Automata', 'Prof. Rajesh Verma', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (59, 'IT214', 'Theory of Computation & Automata', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (220, 'IT211L', 'Linux OS Administration Lab', 'Dr. Amit Patel', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (60, 'IT211L', 'Linux OS Administration Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (221, 'IT301', 'Computer Communication Networks', 'Dr. Priya Nair', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (61, 'IT301', 'Computer Communication Networks', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (222, 'IT302', 'Web Architecture & Full Stack API Design', 'Dr. Amit Patel', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (62, 'IT302', 'Web Architecture & Full Stack API Design', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (223, 'IT303', 'Linux System Administration & Shell Scripting', 'Prof. Rajesh Verma', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (63, 'IT303', 'Linux System Administration & Shell Scripting', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (224, 'IT305', 'Open Source Software Technologies', 'Prof. Sunita Sharma', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (64, 'IT305', 'Open Source Software Technologies', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (225, 'IT301L', 'Network Configuration & Socket Lab', 'Dr. Priya Nair', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (65, 'IT301L', 'Network Configuration & Socket Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (226, 'IT311', 'Cloud Infrastructure & Virtualization', 'Dr. Amit Patel', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (66, 'IT311', 'Cloud Infrastructure & Virtualization', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (227, 'IT312', 'Software Quality Assurance & Automation Testing', 'Prof. Rajesh Verma', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (67, 'IT312', 'Software Quality Assurance & Automation Testing', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (228, 'IT313', 'Information Security & Applied Cryptography', 'Dr. Priya Nair', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (68, 'IT313', 'Information Security & Applied Cryptography', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (229, 'IT315', 'Mobile Application Development (Flutter/Android)', 'Dr. Ramesh Babu', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (69, 'IT315', 'Mobile Application Development (Flutter/Android)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (230, 'IT311L', 'Cloud Microservices & Containers Lab', 'Dr. Amit Patel', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (70, 'IT311L', 'Cloud Microservices & Containers Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (231, 'IT401', 'DevOps & CI/CD Pipeline Automation', 'Dr. Amit Patel', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (71, 'IT401', 'DevOps & CI/CD Pipeline Automation', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (232, 'IT402', 'Big Data Analytics & Hadoop Ecosystem', 'Prof. Sunita Sharma', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (72, 'IT402', 'Big Data Analytics & Hadoop Ecosystem', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (233, 'IT403', 'Enterprise Web Applications Engineering', 'Dr. Ramesh Babu', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (73, 'IT403', 'Enterprise Web Applications Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (234, 'IT405', 'Information Storage & Management', 'Dr. Priya Nair', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (74, 'IT405', 'Information Storage & Management', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (235, 'IT401L', 'DevOps & Containerization Lab', 'Dr. Amit Patel', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (75, 'IT401L', 'DevOps & Containerization Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (236, 'IT411', 'Cloud Security, Governance & Compliance', 'Dr. Amit Patel', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (76, 'IT411', 'Cloud Security, Governance & Compliance', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (237, 'IT413', 'Virtual Reality & Augmented Reality Systems', 'Dr. Ramesh Babu', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (77, 'IT413', 'Virtual Reality & Augmented Reality Systems', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (238, 'IT414', 'Full Stack MEAN/MERN Web Engineering', 'Prof. Sunita Sharma', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (78, 'IT414', 'Full Stack MEAN/MERN Web Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (239, 'IT498', 'IT Industry Capstone Project', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (79, 'IT498', 'IT Industry Capstone Project', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (240, 'IT499', 'Comprehensive Technical Seminar & Viva', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (80, 'IT499', 'Comprehensive Technical Seminar & Viva', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (301, 'EC111', 'Calculus and Complex Variables', 'Dr. Satish Sharma', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (81, 'EC111', 'Calculus and Complex Variables', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (302, 'EC112', 'Engineering Physics for Electronics', 'Prof. Ananya Sen', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (82, 'EC112', 'Engineering Physics for Electronics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (303, 'EC113', 'C Programming for Engineers', 'Dr. Amit Patel', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (83, 'EC113', 'C Programming for Engineers', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (304, 'EC114', 'Basics of Electrical & Electronics Engineering', 'Dr. V. C. Reddy', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (84, 'EC114', 'Basics of Electrical & Electronics Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (305, 'EC111L', 'C Programming Laboratory', 'Dr. Amit Patel', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (85, 'EC111L', 'C Programming Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (306, 'EC121', 'Linear Algebra & Numerical Transforms', 'Dr. Satish Sharma', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (86, 'EC121', 'Linear Algebra & Numerical Transforms', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (307, 'EC122', 'Solid State Chemistry & Materials', 'Prof. Meenakshi Sundaram', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (87, 'EC122', 'Solid State Chemistry & Materials', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (308, 'EC123', 'Electric Circuit Theory & Network Analysis', 'Dr. V. C. Reddy', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (88, 'EC123', 'Electric Circuit Theory & Network Analysis', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (309, 'EC124', 'Electrical Machines & Power Systems', 'Dr. Priya Nair', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (89, 'EC124', 'Electrical Machines & Power Systems', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (310, 'EC121L', 'Electric Circuits & Simulation Lab', 'Dr. V. C. Reddy', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (90, 'EC121L', 'Electric Circuits & Simulation Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (311, 'EC201', 'Electronic Devices & Semiconductor Physics', 'Dr. V. C. Reddy', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (91, 'EC201', 'Electronic Devices & Semiconductor Physics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (312, 'EC202', 'Digital Electronics & Logic Design', 'Dr. Priya Nair', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (92, 'EC202', 'Digital Electronics & Logic Design', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (313, 'EC203', 'Signals, Systems and Transforms', 'Dr. Satish Sharma', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (93, 'EC203', 'Signals, Systems and Transforms', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (314, 'EC204', 'Electromagnetic Fields & Waves', 'Prof. Ananya Sen', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (94, 'EC204', 'Electromagnetic Fields & Waves', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (315, 'EC201L', 'Electronic Devices & Circuits Lab', 'Dr. V. C. Reddy', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (95, 'EC201L', 'Electronic Devices & Circuits Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (316, 'EC211', 'Analog Circuits & Linear Amplifiers', 'Dr. V. C. Reddy', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (96, 'EC211', 'Analog Circuits & Linear Amplifiers', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (317, 'EC212', 'Microprocessors & Microcontroller Interfacing', 'Dr. Priya Nair', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (97, 'EC212', 'Microprocessors & Microcontroller Interfacing', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (318, 'EC213', 'Analog Communication Systems', 'Prof. Ananya Sen', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (98, 'EC213', 'Analog Communication Systems', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (319, 'EC214', 'Linear Integrated Circuits & OP-AMPs', 'Dr. V. C. Reddy', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (99, 'EC214', 'Linear Integrated Circuits & OP-AMPs', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (320, 'EC211L', 'Analog Integrated Circuits Lab', 'Dr. V. C. Reddy', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (100, 'EC211L', 'Analog Integrated Circuits Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (321, 'EC301', 'Digital Communication & Modulation', 'Dr. Priya Nair', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (101, 'EC301', 'Digital Communication & Modulation', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (322, 'EC302', 'Microcontrollers & ARM Architecture', 'Dr. V. C. Reddy', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (102, 'EC302', 'Microcontrollers & ARM Architecture', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (323, 'EC303', 'Digital Signal Processing (DSP)', 'Dr. Satish Sharma', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (103, 'EC303', 'Digital Signal Processing (DSP)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (324, 'EC304', 'Antennas and Radio Wave Propagation', 'Prof. Ananya Sen', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (104, 'EC304', 'Antennas and Radio Wave Propagation', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (325, 'EC301L', 'Digital Communication Laboratory', 'Dr. Priya Nair', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (105, 'EC301L', 'Digital Communication Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (326, 'EC311', 'VLSI Circuit Design & CMOS Technology', 'Dr. V. C. Reddy', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (106, 'EC311', 'VLSI Circuit Design & CMOS Technology', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (327, 'EC312', 'Wireless & Cellular Communications', 'Dr. Priya Nair', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (107, 'EC312', 'Wireless & Cellular Communications', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (328, 'EC313', 'Microwave and Radar Engineering', 'Prof. Ananya Sen', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (108, 'EC313', 'Microwave and Radar Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (329, 'EC314', 'Embedded Real-Time Operating Systems (RTOS)', 'Dr. Amit Patel', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (109, 'EC314', 'Embedded Real-Time Operating Systems (RTOS)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (330, 'EC311L', 'VLSI Design & Cadence EDA Lab', 'Dr. V. C. Reddy', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (110, 'EC311L', 'VLSI Design & Cadence EDA Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (331, 'EC401', 'RF and Microwave Circuit Design', 'Prof. Ananya Sen', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (111, 'EC401', 'RF and Microwave Circuit Design', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (332, 'EC402', 'Satellite and Space Communications', 'Dr. Priya Nair', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (112, 'EC402', 'Satellite and Space Communications', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (333, 'EC403', 'IoT Architecture, Sensors & Actuators', 'Dr. V. C. Reddy', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (113, 'EC403', 'IoT Architecture, Sensors & Actuators', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (334, 'EC405', 'Digital Image & Video Processing', 'Prof. Sunita Sharma', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (114, 'EC405', 'Digital Image & Video Processing', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (335, 'EC401L', 'RF Microwave Measurement Lab', 'Prof. Ananya Sen', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (115, 'EC401L', 'RF Microwave Measurement Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (336, 'EC411', 'Next-Gen 5G/6G Wireless Networks', 'Dr. Priya Nair', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (116, 'EC411', 'Next-Gen 5G/6G Wireless Networks', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (337, 'EC412', 'Mixed Signal CMOS Integrated Circuits', 'Dr. V. C. Reddy', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (117, 'EC412', 'Mixed Signal CMOS Integrated Circuits', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (338, 'EC413', 'Robotics, Automation & Machine Vision', 'Dr. Amit Patel', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (118, 'EC413', 'Robotics, Automation & Machine Vision', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (339, 'EC498', 'Major Capstone Project Phase II', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (119, 'EC498', 'Major Capstone Project Phase II', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (340, 'EC499', 'Comprehensive Technical Viva Voce', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (120, 'EC499', 'Comprehensive Technical Viva Voce', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (401, 'ME111', 'Calculus & Analytical Geometry', 'Dr. Satish Sharma', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (121, 'ME111', 'Calculus & Analytical Geometry', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (402, 'ME112', 'Engineering Physics for Mechanics', 'Prof. Ananya Sen', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (122, 'ME112', 'Engineering Physics for Mechanics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (403, 'ME113', 'Engineering Mechanics (Statics & Dynamics)', 'Dr. K. Srinivas', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (123, 'ME113', 'Engineering Mechanics (Statics & Dynamics)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (404, 'ME114', 'Basic Electrical & Electronics', 'Dr. Priya Nair', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (124, 'ME114', 'Basic Electrical & Electronics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (405, 'ME111L', 'Workshop & Manufacturing Practice Lab', 'Dr. K. Srinivas', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (125, 'ME111L', 'Workshop & Manufacturing Practice Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (406, 'ME121', 'Differential Equations & Laplace Transforms', 'Dr. Satish Sharma', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (126, 'ME121', 'Differential Equations & Laplace Transforms', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (407, 'ME122', 'Materials Science and Engineering Metallurgy', 'Dr. K. Srinivas', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (127, 'ME122', 'Materials Science and Engineering Metallurgy', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (408, 'ME123', 'Computer Programming in C', 'Dr. Amit Patel', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (128, 'ME123', 'Computer Programming in C', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (409, 'ME124', 'Basic Electronics & Instrumentation', 'Dr. V. C. Reddy', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (129, 'ME124', 'Basic Electronics & Instrumentation', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (410, 'ME121L', 'C Programming Laboratory', 'Dr. Amit Patel', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (130, 'ME121L', 'C Programming Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (411, 'ME201', 'Engineering Thermodynamics', 'Dr. K. Srinivas', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (131, 'ME201', 'Engineering Thermodynamics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (412, 'ME202', 'Strength of Materials & Mechanics of Solids', 'Dr. Rajesh Gupta', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (132, 'ME202', 'Strength of Materials & Mechanics of Solids', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (413, 'ME203', 'Manufacturing Technology I (Casting & Welding)', 'Prof. Manoj Kumar', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (133, 'ME203', 'Manufacturing Technology I (Casting & Welding)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (414, 'ME204', 'Fluid Mechanics and Hydraulic Machinery', 'Dr. K. Srinivas', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (134, 'ME204', 'Fluid Mechanics and Hydraulic Machinery', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (415, 'ME202L', 'Strength of Materials Laboratory', 'Dr. Rajesh Gupta', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (135, 'ME202L', 'Strength of Materials Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (416, 'ME211', 'Applied Thermodynamics & Steam Power', 'Dr. K. Srinivas', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (136, 'ME211', 'Applied Thermodynamics & Steam Power', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (417, 'ME212', 'Dynamics of Machinery & Vibrations', 'Prof. Manoj Kumar', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (137, 'ME212', 'Dynamics of Machinery & Vibrations', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (418, 'ME213', 'Manufacturing Technology II (Machining & Forming)', 'Prof. Manoj Kumar', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (138, 'ME213', 'Manufacturing Technology II (Machining & Forming)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (419, 'ME214', 'Mechanical Measurements and Metrology', 'Dr. Rajesh Gupta', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (139, 'ME214', 'Mechanical Measurements and Metrology', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (420, 'ME211L', 'Thermal Engineering Laboratory I', 'Dr. K. Srinivas', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (140, 'ME211L', 'Thermal Engineering Laboratory I', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (421, 'ME301', 'Heat and Mass Transfer', 'Dr. K. Srinivas', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (141, 'ME301', 'Heat and Mass Transfer', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (422, 'ME302', 'Design of Machine Elements I', 'Prof. Manoj Kumar', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (142, 'ME302', 'Design of Machine Elements I', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (423, 'ME303', 'Internal Combustion Engines & Gas Turbines', 'Dr. K. Srinivas', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (143, 'ME303', 'Internal Combustion Engines & Gas Turbines', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (424, 'ME304', 'Automobile Chassis & Powertrain Engineering', 'Prof. Manoj Kumar', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (144, 'ME304', 'Automobile Chassis & Powertrain Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (425, 'ME301L', 'Heat Transfer Laboratory', 'Dr. K. Srinivas', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (145, 'ME301L', 'Heat Transfer Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (426, 'ME311', 'Computer Aided Design & Manufacturing (CAD/CAM)', 'Prof. Manoj Kumar', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (146, 'ME311', 'Computer Aided Design & Manufacturing (CAD/CAM)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (427, 'ME312', 'Design of Transmission Systems & Gears', 'Prof. Manoj Kumar', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (147, 'ME312', 'Design of Transmission Systems & Gears', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (428, 'ME313', 'Finite Element Analysis (FEA)', 'Dr. Rajesh Gupta', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (148, 'ME313', 'Finite Element Analysis (FEA)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (429, 'ME314', 'Refrigeration and Air Conditioning', 'Dr. K. Srinivas', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (149, 'ME314', 'Refrigeration and Air Conditioning', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (430, 'ME311L', 'CAD/CAM & CNC Machining Lab', 'Prof. Manoj Kumar', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (150, 'ME311L', 'CAD/CAM & CNC Machining Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (431, 'ME401', 'Mechatronics and Industrial Automation', 'Dr. Amit Patel', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (151, 'ME401', 'Mechatronics and Industrial Automation', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (432, 'ME402', 'Power Plant Engineering & Energy Systems', 'Dr. K. Srinivas', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (152, 'ME402', 'Power Plant Engineering & Energy Systems', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (433, 'ME403', 'Robotics and Flexible Manufacturing Systems', 'Prof. Manoj Kumar', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (153, 'ME403', 'Robotics and Flexible Manufacturing Systems', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (434, 'ME404', 'Computational Fluid Dynamics (CFD)', 'Dr. K. Srinivas', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (154, 'ME404', 'Computational Fluid Dynamics (CFD)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (435, 'ME401L', 'Mechatronics and Robotics Lab', 'Dr. Amit Patel', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (155, 'ME401L', 'Mechatronics and Robotics Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (436, 'ME411', 'Renewable Energy Technologies & Solar Thermal', 'Dr. K. Srinivas', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (156, 'ME411', 'Renewable Energy Technologies & Solar Thermal', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (437, 'ME412', 'Total Quality Management (TQM) & Six Sigma', 'Prof. Rajesh Verma', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (157, 'ME412', 'Total Quality Management (TQM) & Six Sigma', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (438, 'ME414', 'Electric & Hybrid Vehicle Engineering', 'Prof. Manoj Kumar', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (158, 'ME414', 'Electric & Hybrid Vehicle Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (439, 'ME498', 'Major Capstone Project Phase II', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (159, 'ME498', 'Major Capstone Project Phase II', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (440, 'ME499', 'Comprehensive Technical Viva Voce', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (160, 'ME499', 'Comprehensive Technical Viva Voce', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (501, 'CE111', 'Calculus & Linear Algebra', 'Dr. Satish Sharma', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (161, 'CE111', 'Calculus & Linear Algebra', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (502, 'CE112', 'Engineering Physics for Civil Engineering', 'Prof. Ananya Sen', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (162, 'CE112', 'Engineering Physics for Civil Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (503, 'CE113', 'Engineering Mechanics & Structural Statics', 'Dr. Rajesh Gupta', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (163, 'CE113', 'Engineering Mechanics & Structural Statics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (504, 'CE114', 'Basic Electrical & Mechanical Engineering', 'Dr. K. Srinivas', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (164, 'CE114', 'Basic Electrical & Mechanical Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (505, 'CE111L', 'Civil Workshop Practice Lab', 'Prof. Suresh Reddy', 'Semester 1');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (165, 'CE111L', 'Civil Workshop Practice Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (506, 'CE121', 'Differential Equations & Numerical Methods', 'Dr. Satish Sharma', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (166, 'CE121', 'Differential Equations & Numerical Methods', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (507, 'CE122', 'Engineering Chemistry & Environmental Materials', 'Prof. Meenakshi Sundaram', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (167, 'CE122', 'Engineering Chemistry & Environmental Materials', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (508, 'CE123', 'Problem Solving and Programming in C', 'Dr. Amit Patel', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (168, 'CE123', 'Problem Solving and Programming in C', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (509, 'CE124', 'Building Materials and Construction Practices', 'Prof. Suresh Reddy', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (169, 'CE124', 'Building Materials and Construction Practices', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (510, 'CE121L', 'C Programming Laboratory', 'Dr. Amit Patel', 'Semester 2');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (170, 'CE121L', 'C Programming Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (511, 'CE201', 'Strength of Materials I', 'Dr. Rajesh Gupta', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (171, 'CE201', 'Strength of Materials I', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (512, 'CE202', 'Surveying and Geomatics I', 'Prof. Suresh Reddy', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (172, 'CE202', 'Surveying and Geomatics I', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (513, 'CE203', 'Fluid Mechanics & Open Channel Flow', 'Dr. K. Srinivas', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (173, 'CE203', 'Fluid Mechanics & Open Channel Flow', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (514, 'CE204', 'Engineering Geology and Rock Mechanics', 'Prof. Suresh Reddy', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (174, 'CE204', 'Engineering Geology and Rock Mechanics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (515, 'CE201L', 'Strength of Materials Laboratory', 'Dr. Rajesh Gupta', 'Semester 3');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (175, 'CE201L', 'Strength of Materials Laboratory', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (516, 'CE211', 'Strength of Materials II & Structural Mechanics', 'Dr. Rajesh Gupta', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (176, 'CE211', 'Strength of Materials II & Structural Mechanics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (517, 'CE212', 'Hydraulics and Hydraulic Machinery', 'Dr. K. Srinivas', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (177, 'CE212', 'Hydraulics and Hydraulic Machinery', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (518, 'CE213', 'Structural Analysis I', 'Dr. Rajesh Gupta', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (178, 'CE213', 'Structural Analysis I', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (519, 'CE214', 'Concrete Technology & Mix Design', 'Prof. Suresh Reddy', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (179, 'CE214', 'Concrete Technology & Mix Design', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (520, 'CE212L', 'Fluid Mechanics & Hydraulics Lab', 'Dr. K. Srinivas', 'Semester 4');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (180, 'CE212L', 'Fluid Mechanics & Hydraulics Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (521, 'CE301', 'Structural Analysis II (Matrix Methods)', 'Dr. Rajesh Gupta', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (181, 'CE301', 'Structural Analysis II (Matrix Methods)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (522, 'CE302', 'Design of Reinforced Concrete Structures (RCC)', 'Prof. Suresh Reddy', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (182, 'CE302', 'Design of Reinforced Concrete Structures (RCC)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (523, 'CE303', 'Geotechnical Engineering I (Soil Mechanics)', 'Dr. Rajesh Gupta', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (183, 'CE303', 'Geotechnical Engineering I (Soil Mechanics)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (524, 'CE304', 'Environmental Engineering I (Water Supply)', 'Prof. Meenakshi Sundaram', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (184, 'CE304', 'Environmental Engineering I (Water Supply)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (525, 'CE303L', 'Soil Mechanics & Geotechnical Lab', 'Dr. Rajesh Gupta', 'Semester 5');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (185, 'CE303L', 'Soil Mechanics & Geotechnical Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (526, 'CE311', 'Design of Steel Structures (IS 800)', 'Dr. Rajesh Gupta', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (186, 'CE311', 'Design of Steel Structures (IS 800)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (527, 'CE312', 'Geotechnical Engineering II (Foundation Engineering)', 'Dr. Rajesh Gupta', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (187, 'CE312', 'Geotechnical Engineering II (Foundation Engineering)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (528, 'CE313', 'Environmental Engineering II (Wastewater Treatment)', 'Prof. Meenakshi Sundaram', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (188, 'CE313', 'Environmental Engineering II (Wastewater Treatment)', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (529, 'CE314', 'Highway, Railway & Airport Engineering', 'Prof. Suresh Reddy', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (189, 'CE314', 'Highway, Railway & Airport Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (530, 'CE311L', 'Structural Steel Detailing & STAAD.Pro Lab', 'Dr. Rajesh Gupta', 'Semester 6');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (190, 'CE311L', 'Structural Steel Detailing & STAAD.Pro Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (531, 'CE401', 'Estimation, Costing, Valuation & Specifications', 'Prof. Suresh Reddy', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (191, 'CE401', 'Estimation, Costing, Valuation & Specifications', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (532, 'CE402', 'Design of Prestressed Concrete Structures', 'Dr. Rajesh Gupta', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (192, 'CE402', 'Design of Prestressed Concrete Structures', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (533, 'CE403', 'Construction Planning, Scheduling & Management', 'Prof. Rajesh Verma', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (193, 'CE403', 'Construction Planning, Scheduling & Management', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (534, 'CE404', 'Earthquake Resistant Design of Structures', 'Dr. Rajesh Gupta', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (194, 'CE404', 'Earthquake Resistant Design of Structures', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (535, 'CE401L', 'GIS & Quantity Surveying Software Lab', 'Prof. Suresh Reddy', 'Semester 7');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (195, 'CE401L', 'GIS & Quantity Surveying Software Lab', 'LAB');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (536, 'CE411', 'Bridge Engineering & Structural Design', 'Dr. Rajesh Gupta', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (196, 'CE411', 'Bridge Engineering & Structural Design', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (537, 'CE412', 'Ground Improvement Techniques & Geosynthetics', 'Dr. Rajesh Gupta', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (197, 'CE412', 'Ground Improvement Techniques & Geosynthetics', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (538, 'CE413', 'Urban Transportation Planning & Traffic Engineering', 'Prof. Suresh Reddy', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (198, 'CE413', 'Urban Transportation Planning & Traffic Engineering', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (539, 'CE498', 'Civil Engineering Capstone Project Phase II', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (199, 'CE498', 'Civil Engineering Capstone Project Phase II', 'THEORY');
INSERT INTO courses (id, code, title, faculty, semester) VALUES (540, 'CE499', 'Comprehensive Technical Seminar & Viva Voce', 'Faculty Board', 'Semester 8');
INSERT INTO curriculum_subjects (sub_id, sub_code, subject_name, subject_type) VALUES (200, 'CE499', 'Comprehensive Technical Seminar & Viva Voce', 'THEORY');
SET FOREIGN_KEY_CHECKS = 1;